// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

package monitor.broker;

public final class TokenProto {
  private TokenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TokenMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TokenMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Token token = 1;</code>
     * @return Whether the token field is set.
     */
    boolean hasToken();
    /**
     * <code>.Token token = 1;</code>
     * @return The token.
     */
    monitor.broker.TokenProto.Token getToken();
    /**
     * <code>.Token token = 1;</code>
     */
    monitor.broker.TokenProto.TokenOrBuilder getTokenOrBuilder();

    /**
     * <code>string state = 2;</code>
     * @return The state.
     */
    java.lang.String getState();
    /**
     * <code>string state = 2;</code>
     * @return The bytes for state.
     */
    com.google.protobuf.ByteString
        getStateBytes();

    /**
     * <code>int32 producingId = 3;</code>
     * @return The producingId.
     */
    int getProducingId();
  }
  /**
   * Protobuf type {@code TokenMessage}
   */
  public static final class TokenMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TokenMessage)
      TokenMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TokenMessage.newBuilder() to construct.
    private TokenMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TokenMessage() {
      state_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TokenMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TokenMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              monitor.broker.TokenProto.Token.Builder subBuilder = null;
              if (token_ != null) {
                subBuilder = token_.toBuilder();
              }
              token_ = input.readMessage(monitor.broker.TokenProto.Token.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(token_);
                token_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              state_ = s;
              break;
            }
            case 24: {

              producingId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return monitor.broker.TokenProto.internal_static_TokenMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return monitor.broker.TokenProto.internal_static_TokenMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              monitor.broker.TokenProto.TokenMessage.class, monitor.broker.TokenProto.TokenMessage.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private monitor.broker.TokenProto.Token token_;
    /**
     * <code>.Token token = 1;</code>
     * @return Whether the token field is set.
     */
    @java.lang.Override
    public boolean hasToken() {
      return token_ != null;
    }
    /**
     * <code>.Token token = 1;</code>
     * @return The token.
     */
    @java.lang.Override
    public monitor.broker.TokenProto.Token getToken() {
      return token_ == null ? monitor.broker.TokenProto.Token.getDefaultInstance() : token_;
    }
    /**
     * <code>.Token token = 1;</code>
     */
    @java.lang.Override
    public monitor.broker.TokenProto.TokenOrBuilder getTokenOrBuilder() {
      return getToken();
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object state_;
    /**
     * <code>string state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string state = 2;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCINGID_FIELD_NUMBER = 3;
    private int producingId_;
    /**
     * <code>int32 producingId = 3;</code>
     * @return The producingId.
     */
    @java.lang.Override
    public int getProducingId() {
      return producingId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (token_ != null) {
        output.writeMessage(1, getToken());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, state_);
      }
      if (producingId_ != 0) {
        output.writeInt32(3, producingId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (token_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getToken());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, state_);
      }
      if (producingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, producingId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof monitor.broker.TokenProto.TokenMessage)) {
        return super.equals(obj);
      }
      monitor.broker.TokenProto.TokenMessage other = (monitor.broker.TokenProto.TokenMessage) obj;

      if (hasToken() != other.hasToken()) return false;
      if (hasToken()) {
        if (!getToken()
            .equals(other.getToken())) return false;
      }
      if (!getState()
          .equals(other.getState())) return false;
      if (getProducingId()
          != other.getProducingId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasToken()) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
      }
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (37 * hash) + PRODUCINGID_FIELD_NUMBER;
      hash = (53 * hash) + getProducingId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static monitor.broker.TokenProto.TokenMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.TokenMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.TokenMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(monitor.broker.TokenProto.TokenMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TokenMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TokenMessage)
        monitor.broker.TokenProto.TokenMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return monitor.broker.TokenProto.internal_static_TokenMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return monitor.broker.TokenProto.internal_static_TokenMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                monitor.broker.TokenProto.TokenMessage.class, monitor.broker.TokenProto.TokenMessage.Builder.class);
      }

      // Construct using monitor.broker.TokenProto.TokenMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (tokenBuilder_ == null) {
          token_ = null;
        } else {
          token_ = null;
          tokenBuilder_ = null;
        }
        state_ = "";

        producingId_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return monitor.broker.TokenProto.internal_static_TokenMessage_descriptor;
      }

      @java.lang.Override
      public monitor.broker.TokenProto.TokenMessage getDefaultInstanceForType() {
        return monitor.broker.TokenProto.TokenMessage.getDefaultInstance();
      }

      @java.lang.Override
      public monitor.broker.TokenProto.TokenMessage build() {
        monitor.broker.TokenProto.TokenMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public monitor.broker.TokenProto.TokenMessage buildPartial() {
        monitor.broker.TokenProto.TokenMessage result = new monitor.broker.TokenProto.TokenMessage(this);
        if (tokenBuilder_ == null) {
          result.token_ = token_;
        } else {
          result.token_ = tokenBuilder_.build();
        }
        result.state_ = state_;
        result.producingId_ = producingId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof monitor.broker.TokenProto.TokenMessage) {
          return mergeFrom((monitor.broker.TokenProto.TokenMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(monitor.broker.TokenProto.TokenMessage other) {
        if (other == monitor.broker.TokenProto.TokenMessage.getDefaultInstance()) return this;
        if (other.hasToken()) {
          mergeToken(other.getToken());
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          onChanged();
        }
        if (other.getProducingId() != 0) {
          setProducingId(other.getProducingId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        monitor.broker.TokenProto.TokenMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (monitor.broker.TokenProto.TokenMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private monitor.broker.TokenProto.Token token_;
      private com.google.protobuf.SingleFieldBuilderV3<
          monitor.broker.TokenProto.Token, monitor.broker.TokenProto.Token.Builder, monitor.broker.TokenProto.TokenOrBuilder> tokenBuilder_;
      /**
       * <code>.Token token = 1;</code>
       * @return Whether the token field is set.
       */
      public boolean hasToken() {
        return tokenBuilder_ != null || token_ != null;
      }
      /**
       * <code>.Token token = 1;</code>
       * @return The token.
       */
      public monitor.broker.TokenProto.Token getToken() {
        if (tokenBuilder_ == null) {
          return token_ == null ? monitor.broker.TokenProto.Token.getDefaultInstance() : token_;
        } else {
          return tokenBuilder_.getMessage();
        }
      }
      /**
       * <code>.Token token = 1;</code>
       */
      public Builder setToken(monitor.broker.TokenProto.Token value) {
        if (tokenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          token_ = value;
          onChanged();
        } else {
          tokenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Token token = 1;</code>
       */
      public Builder setToken(
          monitor.broker.TokenProto.Token.Builder builderForValue) {
        if (tokenBuilder_ == null) {
          token_ = builderForValue.build();
          onChanged();
        } else {
          tokenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Token token = 1;</code>
       */
      public Builder mergeToken(monitor.broker.TokenProto.Token value) {
        if (tokenBuilder_ == null) {
          if (token_ != null) {
            token_ =
              monitor.broker.TokenProto.Token.newBuilder(token_).mergeFrom(value).buildPartial();
          } else {
            token_ = value;
          }
          onChanged();
        } else {
          tokenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Token token = 1;</code>
       */
      public Builder clearToken() {
        if (tokenBuilder_ == null) {
          token_ = null;
          onChanged();
        } else {
          token_ = null;
          tokenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Token token = 1;</code>
       */
      public monitor.broker.TokenProto.Token.Builder getTokenBuilder() {
        
        onChanged();
        return getTokenFieldBuilder().getBuilder();
      }
      /**
       * <code>.Token token = 1;</code>
       */
      public monitor.broker.TokenProto.TokenOrBuilder getTokenOrBuilder() {
        if (tokenBuilder_ != null) {
          return tokenBuilder_.getMessageOrBuilder();
        } else {
          return token_ == null ?
              monitor.broker.TokenProto.Token.getDefaultInstance() : token_;
        }
      }
      /**
       * <code>.Token token = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          monitor.broker.TokenProto.Token, monitor.broker.TokenProto.Token.Builder, monitor.broker.TokenProto.TokenOrBuilder> 
          getTokenFieldBuilder() {
        if (tokenBuilder_ == null) {
          tokenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              monitor.broker.TokenProto.Token, monitor.broker.TokenProto.Token.Builder, monitor.broker.TokenProto.TokenOrBuilder>(
                  getToken(),
                  getParentForChildren(),
                  isClean());
          token_ = null;
        }
        return tokenBuilder_;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string state = 2;</code>
       * @return The state.
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string state = 2;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string state = 2;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string state = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = getDefaultInstance().getState();
        onChanged();
        return this;
      }
      /**
       * <code>string state = 2;</code>
       * @param value The bytes for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        state_ = value;
        onChanged();
        return this;
      }

      private int producingId_ ;
      /**
       * <code>int32 producingId = 3;</code>
       * @return The producingId.
       */
      @java.lang.Override
      public int getProducingId() {
        return producingId_;
      }
      /**
       * <code>int32 producingId = 3;</code>
       * @param value The producingId to set.
       * @return This builder for chaining.
       */
      public Builder setProducingId(int value) {
        
        producingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 producingId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearProducingId() {
        
        producingId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TokenMessage)
    }

    // @@protoc_insertion_point(class_scope:TokenMessage)
    private static final monitor.broker.TokenProto.TokenMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new monitor.broker.TokenProto.TokenMessage();
    }

    public static monitor.broker.TokenProto.TokenMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TokenMessage>
        PARSER = new com.google.protobuf.AbstractParser<TokenMessage>() {
      @java.lang.Override
      public TokenMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TokenMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TokenMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public monitor.broker.TokenProto.TokenMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Token)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    java.util.List<monitor.broker.TokenProto.RequestMessage> 
        getQueueList();
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    monitor.broker.TokenProto.RequestMessage getQueue(int index);
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    int getQueueCount();
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    java.util.List<? extends monitor.broker.TokenProto.RequestMessageOrBuilder> 
        getQueueOrBuilderList();
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    monitor.broker.TokenProto.RequestMessageOrBuilder getQueueOrBuilder(
        int index);

    /**
     * <code>repeated int32 ln = 2;</code>
     * @return A list containing the ln.
     */
    java.util.List<java.lang.Integer> getLnList();
    /**
     * <code>repeated int32 ln = 2;</code>
     * @return The count of ln.
     */
    int getLnCount();
    /**
     * <code>repeated int32 ln = 2;</code>
     * @param index The index of the element to return.
     * @return The ln at the given index.
     */
    int getLn(int index);
  }
  /**
   * Protobuf type {@code Token}
   */
  public static final class Token extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Token)
      TokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Token.newBuilder() to construct.
    private Token(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Token() {
      queue_ = java.util.Collections.emptyList();
      ln_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Token();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Token(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                queue_ = new java.util.ArrayList<monitor.broker.TokenProto.RequestMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              queue_.add(
                  input.readMessage(monitor.broker.TokenProto.RequestMessage.parser(), extensionRegistry));
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                ln_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              ln_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                ln_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                ln_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          queue_ = java.util.Collections.unmodifiableList(queue_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          ln_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return monitor.broker.TokenProto.internal_static_Token_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return monitor.broker.TokenProto.internal_static_Token_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              monitor.broker.TokenProto.Token.class, monitor.broker.TokenProto.Token.Builder.class);
    }

    public static final int QUEUE_FIELD_NUMBER = 1;
    private java.util.List<monitor.broker.TokenProto.RequestMessage> queue_;
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    @java.lang.Override
    public java.util.List<monitor.broker.TokenProto.RequestMessage> getQueueList() {
      return queue_;
    }
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends monitor.broker.TokenProto.RequestMessageOrBuilder> 
        getQueueOrBuilderList() {
      return queue_;
    }
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    @java.lang.Override
    public int getQueueCount() {
      return queue_.size();
    }
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    @java.lang.Override
    public monitor.broker.TokenProto.RequestMessage getQueue(int index) {
      return queue_.get(index);
    }
    /**
     * <code>repeated .RequestMessage queue = 1;</code>
     */
    @java.lang.Override
    public monitor.broker.TokenProto.RequestMessageOrBuilder getQueueOrBuilder(
        int index) {
      return queue_.get(index);
    }

    public static final int LN_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList ln_;
    /**
     * <code>repeated int32 ln = 2;</code>
     * @return A list containing the ln.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getLnList() {
      return ln_;
    }
    /**
     * <code>repeated int32 ln = 2;</code>
     * @return The count of ln.
     */
    public int getLnCount() {
      return ln_.size();
    }
    /**
     * <code>repeated int32 ln = 2;</code>
     * @param index The index of the element to return.
     * @return The ln at the given index.
     */
    public int getLn(int index) {
      return ln_.getInt(index);
    }
    private int lnMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < queue_.size(); i++) {
        output.writeMessage(1, queue_.get(i));
      }
      if (getLnList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(lnMemoizedSerializedSize);
      }
      for (int i = 0; i < ln_.size(); i++) {
        output.writeInt32NoTag(ln_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < queue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, queue_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < ln_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(ln_.getInt(i));
        }
        size += dataSize;
        if (!getLnList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        lnMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof monitor.broker.TokenProto.Token)) {
        return super.equals(obj);
      }
      monitor.broker.TokenProto.Token other = (monitor.broker.TokenProto.Token) obj;

      if (!getQueueList()
          .equals(other.getQueueList())) return false;
      if (!getLnList()
          .equals(other.getLnList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQueueCount() > 0) {
        hash = (37 * hash) + QUEUE_FIELD_NUMBER;
        hash = (53 * hash) + getQueueList().hashCode();
      }
      if (getLnCount() > 0) {
        hash = (37 * hash) + LN_FIELD_NUMBER;
        hash = (53 * hash) + getLnList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static monitor.broker.TokenProto.Token parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.Token parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.Token parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.Token parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.Token parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.Token parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.Token parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.Token parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static monitor.broker.TokenProto.Token parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.Token parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static monitor.broker.TokenProto.Token parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.Token parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(monitor.broker.TokenProto.Token prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Token}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Token)
        monitor.broker.TokenProto.TokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return monitor.broker.TokenProto.internal_static_Token_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return monitor.broker.TokenProto.internal_static_Token_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                monitor.broker.TokenProto.Token.class, monitor.broker.TokenProto.Token.Builder.class);
      }

      // Construct using monitor.broker.TokenProto.Token.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getQueueFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (queueBuilder_ == null) {
          queue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          queueBuilder_.clear();
        }
        ln_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return monitor.broker.TokenProto.internal_static_Token_descriptor;
      }

      @java.lang.Override
      public monitor.broker.TokenProto.Token getDefaultInstanceForType() {
        return monitor.broker.TokenProto.Token.getDefaultInstance();
      }

      @java.lang.Override
      public monitor.broker.TokenProto.Token build() {
        monitor.broker.TokenProto.Token result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public monitor.broker.TokenProto.Token buildPartial() {
        monitor.broker.TokenProto.Token result = new monitor.broker.TokenProto.Token(this);
        int from_bitField0_ = bitField0_;
        if (queueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            queue_ = java.util.Collections.unmodifiableList(queue_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.queue_ = queue_;
        } else {
          result.queue_ = queueBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          ln_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.ln_ = ln_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof monitor.broker.TokenProto.Token) {
          return mergeFrom((monitor.broker.TokenProto.Token)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(monitor.broker.TokenProto.Token other) {
        if (other == monitor.broker.TokenProto.Token.getDefaultInstance()) return this;
        if (queueBuilder_ == null) {
          if (!other.queue_.isEmpty()) {
            if (queue_.isEmpty()) {
              queue_ = other.queue_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureQueueIsMutable();
              queue_.addAll(other.queue_);
            }
            onChanged();
          }
        } else {
          if (!other.queue_.isEmpty()) {
            if (queueBuilder_.isEmpty()) {
              queueBuilder_.dispose();
              queueBuilder_ = null;
              queue_ = other.queue_;
              bitField0_ = (bitField0_ & ~0x00000001);
              queueBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getQueueFieldBuilder() : null;
            } else {
              queueBuilder_.addAllMessages(other.queue_);
            }
          }
        }
        if (!other.ln_.isEmpty()) {
          if (ln_.isEmpty()) {
            ln_ = other.ln_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLnIsMutable();
            ln_.addAll(other.ln_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        monitor.broker.TokenProto.Token parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (monitor.broker.TokenProto.Token) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<monitor.broker.TokenProto.RequestMessage> queue_ =
        java.util.Collections.emptyList();
      private void ensureQueueIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          queue_ = new java.util.ArrayList<monitor.broker.TokenProto.RequestMessage>(queue_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          monitor.broker.TokenProto.RequestMessage, monitor.broker.TokenProto.RequestMessage.Builder, monitor.broker.TokenProto.RequestMessageOrBuilder> queueBuilder_;

      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public java.util.List<monitor.broker.TokenProto.RequestMessage> getQueueList() {
        if (queueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(queue_);
        } else {
          return queueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public int getQueueCount() {
        if (queueBuilder_ == null) {
          return queue_.size();
        } else {
          return queueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public monitor.broker.TokenProto.RequestMessage getQueue(int index) {
        if (queueBuilder_ == null) {
          return queue_.get(index);
        } else {
          return queueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder setQueue(
          int index, monitor.broker.TokenProto.RequestMessage value) {
        if (queueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQueueIsMutable();
          queue_.set(index, value);
          onChanged();
        } else {
          queueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder setQueue(
          int index, monitor.broker.TokenProto.RequestMessage.Builder builderForValue) {
        if (queueBuilder_ == null) {
          ensureQueueIsMutable();
          queue_.set(index, builderForValue.build());
          onChanged();
        } else {
          queueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder addQueue(monitor.broker.TokenProto.RequestMessage value) {
        if (queueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQueueIsMutable();
          queue_.add(value);
          onChanged();
        } else {
          queueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder addQueue(
          int index, monitor.broker.TokenProto.RequestMessage value) {
        if (queueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQueueIsMutable();
          queue_.add(index, value);
          onChanged();
        } else {
          queueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder addQueue(
          monitor.broker.TokenProto.RequestMessage.Builder builderForValue) {
        if (queueBuilder_ == null) {
          ensureQueueIsMutable();
          queue_.add(builderForValue.build());
          onChanged();
        } else {
          queueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder addQueue(
          int index, monitor.broker.TokenProto.RequestMessage.Builder builderForValue) {
        if (queueBuilder_ == null) {
          ensureQueueIsMutable();
          queue_.add(index, builderForValue.build());
          onChanged();
        } else {
          queueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder addAllQueue(
          java.lang.Iterable<? extends monitor.broker.TokenProto.RequestMessage> values) {
        if (queueBuilder_ == null) {
          ensureQueueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, queue_);
          onChanged();
        } else {
          queueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder clearQueue() {
        if (queueBuilder_ == null) {
          queue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          queueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public Builder removeQueue(int index) {
        if (queueBuilder_ == null) {
          ensureQueueIsMutable();
          queue_.remove(index);
          onChanged();
        } else {
          queueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public monitor.broker.TokenProto.RequestMessage.Builder getQueueBuilder(
          int index) {
        return getQueueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public monitor.broker.TokenProto.RequestMessageOrBuilder getQueueOrBuilder(
          int index) {
        if (queueBuilder_ == null) {
          return queue_.get(index);  } else {
          return queueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public java.util.List<? extends monitor.broker.TokenProto.RequestMessageOrBuilder> 
           getQueueOrBuilderList() {
        if (queueBuilder_ != null) {
          return queueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(queue_);
        }
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public monitor.broker.TokenProto.RequestMessage.Builder addQueueBuilder() {
        return getQueueFieldBuilder().addBuilder(
            monitor.broker.TokenProto.RequestMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public monitor.broker.TokenProto.RequestMessage.Builder addQueueBuilder(
          int index) {
        return getQueueFieldBuilder().addBuilder(
            index, monitor.broker.TokenProto.RequestMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .RequestMessage queue = 1;</code>
       */
      public java.util.List<monitor.broker.TokenProto.RequestMessage.Builder> 
           getQueueBuilderList() {
        return getQueueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          monitor.broker.TokenProto.RequestMessage, monitor.broker.TokenProto.RequestMessage.Builder, monitor.broker.TokenProto.RequestMessageOrBuilder> 
          getQueueFieldBuilder() {
        if (queueBuilder_ == null) {
          queueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              monitor.broker.TokenProto.RequestMessage, monitor.broker.TokenProto.RequestMessage.Builder, monitor.broker.TokenProto.RequestMessageOrBuilder>(
                  queue_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          queue_ = null;
        }
        return queueBuilder_;
      }

      private com.google.protobuf.Internal.IntList ln_ = emptyIntList();
      private void ensureLnIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          ln_ = mutableCopy(ln_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 ln = 2;</code>
       * @return A list containing the ln.
       */
      public java.util.List<java.lang.Integer>
          getLnList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(ln_) : ln_;
      }
      /**
       * <code>repeated int32 ln = 2;</code>
       * @return The count of ln.
       */
      public int getLnCount() {
        return ln_.size();
      }
      /**
       * <code>repeated int32 ln = 2;</code>
       * @param index The index of the element to return.
       * @return The ln at the given index.
       */
      public int getLn(int index) {
        return ln_.getInt(index);
      }
      /**
       * <code>repeated int32 ln = 2;</code>
       * @param index The index to set the value at.
       * @param value The ln to set.
       * @return This builder for chaining.
       */
      public Builder setLn(
          int index, int value) {
        ensureLnIsMutable();
        ln_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ln = 2;</code>
       * @param value The ln to add.
       * @return This builder for chaining.
       */
      public Builder addLn(int value) {
        ensureLnIsMutable();
        ln_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ln = 2;</code>
       * @param values The ln to add.
       * @return This builder for chaining.
       */
      public Builder addAllLn(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLnIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ln_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 ln = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLn() {
        ln_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Token)
    }

    // @@protoc_insertion_point(class_scope:Token)
    private static final monitor.broker.TokenProto.Token DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new monitor.broker.TokenProto.Token();
    }

    public static monitor.broker.TokenProto.Token getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Token>
        PARSER = new com.google.protobuf.AbstractParser<Token>() {
      @java.lang.Override
      public Token parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Token(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Token> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Token> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public monitor.broker.TokenProto.Token getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 processId = 1;</code>
     * @return The processId.
     */
    int getProcessId();

    /**
     * <code>int32 number = 2;</code>
     * @return The number.
     */
    int getNumber();

    /**
     * <code>int32 requiredId = 3;</code>
     * @return The requiredId.
     */
    int getRequiredId();

    /**
     * <code>bool failed = 4;</code>
     * @return The failed.
     */
    boolean getFailed();
  }
  /**
   * Protobuf type {@code RequestMessage}
   */
  public static final class RequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestMessage)
      RequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              processId_ = input.readInt32();
              break;
            }
            case 16: {

              number_ = input.readInt32();
              break;
            }
            case 24: {

              requiredId_ = input.readInt32();
              break;
            }
            case 32: {

              failed_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return monitor.broker.TokenProto.internal_static_RequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return monitor.broker.TokenProto.internal_static_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              monitor.broker.TokenProto.RequestMessage.class, monitor.broker.TokenProto.RequestMessage.Builder.class);
    }

    public static final int PROCESSID_FIELD_NUMBER = 1;
    private int processId_;
    /**
     * <code>int32 processId = 1;</code>
     * @return The processId.
     */
    @java.lang.Override
    public int getProcessId() {
      return processId_;
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_;
    /**
     * <code>int32 number = 2;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }

    public static final int REQUIREDID_FIELD_NUMBER = 3;
    private int requiredId_;
    /**
     * <code>int32 requiredId = 3;</code>
     * @return The requiredId.
     */
    @java.lang.Override
    public int getRequiredId() {
      return requiredId_;
    }

    public static final int FAILED_FIELD_NUMBER = 4;
    private boolean failed_;
    /**
     * <code>bool failed = 4;</code>
     * @return The failed.
     */
    @java.lang.Override
    public boolean getFailed() {
      return failed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (processId_ != 0) {
        output.writeInt32(1, processId_);
      }
      if (number_ != 0) {
        output.writeInt32(2, number_);
      }
      if (requiredId_ != 0) {
        output.writeInt32(3, requiredId_);
      }
      if (failed_ != false) {
        output.writeBool(4, failed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (processId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, processId_);
      }
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, number_);
      }
      if (requiredId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, requiredId_);
      }
      if (failed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, failed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof monitor.broker.TokenProto.RequestMessage)) {
        return super.equals(obj);
      }
      monitor.broker.TokenProto.RequestMessage other = (monitor.broker.TokenProto.RequestMessage) obj;

      if (getProcessId()
          != other.getProcessId()) return false;
      if (getNumber()
          != other.getNumber()) return false;
      if (getRequiredId()
          != other.getRequiredId()) return false;
      if (getFailed()
          != other.getFailed()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
      hash = (53 * hash) + getProcessId();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (37 * hash) + REQUIREDID_FIELD_NUMBER;
      hash = (53 * hash) + getRequiredId();
      hash = (37 * hash) + FAILED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getFailed());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static monitor.broker.TokenProto.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static monitor.broker.TokenProto.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(monitor.broker.TokenProto.RequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMessage)
        monitor.broker.TokenProto.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return monitor.broker.TokenProto.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return monitor.broker.TokenProto.internal_static_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                monitor.broker.TokenProto.RequestMessage.class, monitor.broker.TokenProto.RequestMessage.Builder.class);
      }

      // Construct using monitor.broker.TokenProto.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        processId_ = 0;

        number_ = 0;

        requiredId_ = 0;

        failed_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return monitor.broker.TokenProto.internal_static_RequestMessage_descriptor;
      }

      @java.lang.Override
      public monitor.broker.TokenProto.RequestMessage getDefaultInstanceForType() {
        return monitor.broker.TokenProto.RequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public monitor.broker.TokenProto.RequestMessage build() {
        monitor.broker.TokenProto.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public monitor.broker.TokenProto.RequestMessage buildPartial() {
        monitor.broker.TokenProto.RequestMessage result = new monitor.broker.TokenProto.RequestMessage(this);
        result.processId_ = processId_;
        result.number_ = number_;
        result.requiredId_ = requiredId_;
        result.failed_ = failed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof monitor.broker.TokenProto.RequestMessage) {
          return mergeFrom((monitor.broker.TokenProto.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(monitor.broker.TokenProto.RequestMessage other) {
        if (other == monitor.broker.TokenProto.RequestMessage.getDefaultInstance()) return this;
        if (other.getProcessId() != 0) {
          setProcessId(other.getProcessId());
        }
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        if (other.getRequiredId() != 0) {
          setRequiredId(other.getRequiredId());
        }
        if (other.getFailed() != false) {
          setFailed(other.getFailed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        monitor.broker.TokenProto.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (monitor.broker.TokenProto.RequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int processId_ ;
      /**
       * <code>int32 processId = 1;</code>
       * @return The processId.
       */
      @java.lang.Override
      public int getProcessId() {
        return processId_;
      }
      /**
       * <code>int32 processId = 1;</code>
       * @param value The processId to set.
       * @return This builder for chaining.
       */
      public Builder setProcessId(int value) {
        
        processId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 processId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProcessId() {
        
        processId_ = 0;
        onChanged();
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 2;</code>
       * @return The number.
       */
      @java.lang.Override
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 2;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = 0;
        onChanged();
        return this;
      }

      private int requiredId_ ;
      /**
       * <code>int32 requiredId = 3;</code>
       * @return The requiredId.
       */
      @java.lang.Override
      public int getRequiredId() {
        return requiredId_;
      }
      /**
       * <code>int32 requiredId = 3;</code>
       * @param value The requiredId to set.
       * @return This builder for chaining.
       */
      public Builder setRequiredId(int value) {
        
        requiredId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 requiredId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequiredId() {
        
        requiredId_ = 0;
        onChanged();
        return this;
      }

      private boolean failed_ ;
      /**
       * <code>bool failed = 4;</code>
       * @return The failed.
       */
      @java.lang.Override
      public boolean getFailed() {
        return failed_;
      }
      /**
       * <code>bool failed = 4;</code>
       * @param value The failed to set.
       * @return This builder for chaining.
       */
      public Builder setFailed(boolean value) {
        
        failed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool failed = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFailed() {
        
        failed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestMessage)
    }

    // @@protoc_insertion_point(class_scope:RequestMessage)
    private static final monitor.broker.TokenProto.RequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new monitor.broker.TokenProto.RequestMessage();
    }

    public static monitor.broker.TokenProto.RequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<RequestMessage>() {
      @java.lang.Override
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public monitor.broker.TokenProto.RequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Token_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Token_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013token.proto\"I\n\014TokenMessage\022\025\n\005token\030\001" +
      " \001(\0132\006.Token\022\r\n\005state\030\002 \001(\t\022\023\n\013producing" +
      "Id\030\003 \001(\005\"3\n\005Token\022\036\n\005queue\030\001 \003(\0132\017.Reque" +
      "stMessage\022\n\n\002ln\030\002 \003(\005\"W\n\016RequestMessage\022" +
      "\021\n\tprocessId\030\001 \001(\005\022\016\n\006number\030\002 \001(\005\022\022\n\nre" +
      "quiredId\030\003 \001(\005\022\016\n\006failed\030\004 \001(\010B\034\n\016monito" +
      "r.brokerB\nTokenProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TokenMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TokenMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenMessage_descriptor,
        new java.lang.String[] { "Token", "State", "ProducingId", });
    internal_static_Token_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Token_descriptor,
        new java.lang.String[] { "Queue", "Ln", });
    internal_static_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMessage_descriptor,
        new java.lang.String[] { "ProcessId", "Number", "RequiredId", "Failed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
